version: "3.7"
services:
  postgres:
    image: postgis/postgis:13-master
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=senne
      - POSTGRES_PASSWORD=SomePass@
      - POSTGRES_DB=liquor
